version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WebHookDeploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ofghlbcq9p7j"
s3_prefix = "WebHookDeploy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
